language: node_js
node_js:
  - '12.14.0'

cache:
  directories:
    - node_modules
  yarn: true

deploy:
  - provider: script
    script: deploy.sh
    skip_cleanup: true
    on:
      branch: master
